export const pets = [
  {
    id: 1,
    name: 'Коко',
    category: 'dogs',
    type: 'Собака',
    age: '4 года',
    description: 'Ласковая и активная собака, которая ищет дом.',
    image: './assets/dogs/dog-1.jpg',
    donationAmounts: [3000, 7000, 13000],
  },
  {
    id: 2,
    name: 'Чарли',
    category: 'dogs',
    type: 'Собака',
    age: '3 года',
    description: 'Добрый и общительный пёс, любит людей и прогулки.',
    image: './assets/dogs/dog-2.jpg',
    donationAmounts: [3000, 7000, 13000],
  },
  {
    id: 3,
    name: 'Луна',
    category: 'dogs',
    type: 'Собака',
    age: '5 лет',
    description: 'Спокойная собака, которой нужен заботливый хозяин.',
    image: './assets/dogs/dog-3.jpg',
    donationAmounts: [3000, 7000, 13000],
  },
  {
    id: 4,
    name: 'Ричи',
    category: 'dogs',
    type: 'Собака',
    age: '2 года',
    description: 'Энергичный и дружелюбный пёс, готовый к новой семье.',
    image: './assets/dogs/dog-4.jpg',
    donationAmounts: [3000, 7000, 13000],
  },
  {
    id: 5,
    name: 'Боня',
    category: 'dogs',
    type: 'Собака',
    age: '6 лет',
    description: 'Нежная и доверчивая собака с мягким характером.',
    image: './assets/dogs/dog-5.jpg',
    donationAmounts: [3000, 7000, 13000],
  },
  {
    id: 6,
    name: 'Марс',
    category: 'dogs',
    type: 'Собака',
    age: '3 года',
    description: 'Любознательный пёс, которому очень нужен свой человек.',
    image: './assets/dogs/dog-6.jpg',
    donationAmounts: [3000, 7000, 13000],
  },
  {
    id: 7,
    name: 'Рэй',
    category: 'dogs',
    type: 'Собака',
    age: '7 лет',
    description: 'Верный и спокойный пёс, хорошо ладит с людьми.',
    image: './assets/dogs/dog-7.jpg',
    donationAmounts: [3000, 7000, 13000],
  },
  {
    id: 8,
    name: 'Альма',
    category: 'dogs',
    type: 'Собака',
    age: '4 года',
    description: 'Добрая собака, которая мечтает о доме и семье.',
    image: './assets/dogs/dog-8.jpg',
    donationAmounts: [3000, 7000, 13000],
  },
  {
    id: 9,
    name: 'Соня',
    category: 'cats',
    type: 'Кошка',
    age: '2 года',
    description: 'Ласковая кошка, которая любит спокойствие и внимание.',
    image: './assets/cats/cat-1.jpg',
    donationAmounts: [3000, 13000],
  },
  {
    id: 10,
    name: 'Бенедикт',
    category: 'cats',
    type: 'Кот',
    age: '3 года',
    description: 'Общительный кот, готовый познакомиться с новой семьёй.',
    image: './assets/cats/cat-2.jpg',
    donationAmounts: [3000, 13000],
  },
];

export const donationOptions = {
  3000: 'корм',
  7000: 'занятия с кинологом',
  13000: 'передержка',
};
