export const pets = [
  {
    id: 1,
    name: 'Коко',
    category: 'dogs',
    type: 'Собака',
    age: '4 года',
    description: 'Ласковая и активная собака, которая ищет дом.',
    image: './assets/dogs/dog-1.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здорова',
    },
    compatibility: {
      dogs: 'Подходит',
      cats: 'Нужно знакомство',
      children: 'Подходит для семьи с детьми старше 7 лет',
    },
  },
  {
    id: 2,
    name: 'Чарли',
    category: 'dogs',
    type: 'Собака',
    age: '3 года',
    description: 'Добрый и общительный пёс, любит людей и прогулки.',
    image: './assets/dogs/dog-2.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здоров',
    },
    compatibility: {
      dogs: 'Хорошо ладит с собаками',
      cats: 'Нужно знакомство',
      children: 'Подходит для семьи с детьми',
    },
  },
  {
    id: 3,
    name: 'Луна',
    category: 'dogs',
    type: 'Собака',
    age: '5 лет',
    description: 'Спокойная собака, которой нужен заботливый хозяин.',
    image: './assets/dogs/dog-3.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здорова',
    },
    compatibility: {
      dogs: 'Подходит',
      cats: 'Подходит',
      children: 'Лучше для семьи с детьми старше 10 лет',
    },
  },
  {
    id: 4,
    name: 'Ричи',
    category: 'dogs',
    type: 'Собака',
    age: '2 года',
    description: 'Энергичный и дружелюбный пёс, готовый к новой семье.',
    image: './assets/dogs/dog-4.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здоров',
    },
    compatibility: {
      dogs: 'Хорошо ладит с собаками',
      cats: 'Нужно знакомство',
      children: 'Подходит для активной семьи с детьми старше 7 лет',
    },
  },
  {
    id: 5,
    name: 'Боня',
    category: 'dogs',
    type: 'Собака',
    age: '6 лет',
    description: 'Нежная и доверчивая собака с мягким характером.',
    image: './assets/dogs/dog-5.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здорова',
    },
    compatibility: {
      dogs: 'Подходит',
      cats: 'Подходит',
      children: 'Подходит для спокойной семьи с детьми',
    },
  },
  {
    id: 6,
    name: 'Марс',
    category: 'dogs',
    type: 'Собака',
    age: '3 года',
    description: 'Любознательный пёс, которому очень нужен свой человек.',
    image: './assets/dogs/dog-6.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здоров',
    },
    compatibility: {
      dogs: 'Нужно знакомство',
      cats: 'Лучше без кошек',
      children: 'Подходит для семьи с детьми старше 12 лет',
    },
  },
  {
    id: 7,
    name: 'Рэй',
    category: 'dogs',
    type: 'Собака',
    age: '7 лет',
    description: 'Верный и спокойный пёс, хорошо ладит с людьми.',
    image: './assets/dogs/dog-7.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здоров, требуется возрастной контроль здоровья',
    },
    compatibility: {
      dogs: 'Подходит',
      cats: 'Подходит',
      children: 'Подходит для спокойной семьи с детьми старше 7 лет',
    },
  },
  {
    id: 8,
    name: 'Альма',
    category: 'dogs',
    type: 'Собака',
    age: '4 года',
    description: 'Добрая собака, которая мечтает о доме и семье.',
    image: './assets/dogs/dog-8.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здорова',
    },
    compatibility: {
      dogs: 'Подходит',
      cats: 'Нужно знакомство',
      children: 'Подходит для семьи с детьми',
    },
  },
  {
    id: 9,
    name: 'Соня',
    category: 'cats',
    type: 'Кошка',
    age: '2 года',
    description: 'Ласковая кошка, которая любит спокойствие и внимание.',
    image: './assets/cats/cat-1.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здорова',
    },
    compatibility: {
      dogs: 'Нужно знакомство',
      cats: 'Подходит',
      children: 'Подходит для спокойной семьи с детьми старше 7 лет',
    },
  },
  {
    id: 10,
    name: 'Бенедикт',
    category: 'cats',
    type: 'Кот',
    age: '3 года',
    description: 'Общительный кот, готовый познакомиться с новой семьёй.',
    image: './assets/cats/cat-2.jpg',
    health: {
      vaccinated: true,
      sterilized: true,
      status: 'Здоров',
    },
    compatibility: {
      dogs: 'Нужно знакомство',
      cats: 'Хорошо ладит с кошками',
      children: 'Подходит для семьи с детьми',
    },
  },
];
